### ISSUE TITLE
This extension violates the Chrome Web Store policy.

### ISSUE THREAD

**Issue by XChrispy** [sutuboss/Copy-Past-Pro#2]
This extension has been removed from the Chrome Web Store and remotely from all user's Chrome browsers due to an apparent violation of the Chrome Web Store policy.

This is obviously highly concerning as I am left wondering if my personal data has been stolen by the author.

Does anyone have an update as to what happened?

Web Store link: https://chrome.google.com/webstore/detail/epgndihjbcepnbadocaoofjnfaophlio
Mirror/cache: https://chrome-stats.com/d/epgndihjbcepnbadocaoofjnfaophlio

**Comment by sutuboss** [comment]
@XChrispy , The Extension is up. We don't track any of your Personal Data. Read the Privacy Policy of the Extension to know more..

**Comment by XChrispy** [comment]
@sutuboss Thanks for your reply. I appreciate you have a privacy policy, but policies aren't always followed. Being removed from the Chrome Web Store indicates their privacy policy or terms of use were broken. Therefore can you please elaborate on why the extension was previously taken down?

**Comment by sutuboss** [comment]
@XChrispy , it was taken down mainly for 2 reasons. First, I was required to add the Privacy Policy which I didn't have initially, and the second was about some permission which I requested in the extension but was not using it. So I had to remove it to get the extension approved.

**Comment by XChrispy** [comment]
@sutuboss Okay thank you
